import {
  Video,
  Wand2,
  Mic2,
  Users,
  ShoppingBag,
  MessageSquare,
  TrendingUp,
  Briefcase,
  Settings,
  Code2,
  Cpu,
  HeadphonesIcon,
  LineChart,
} from "lucide-react";

export const platforms = [
  {
    id: "vidyo-ai",
    name: "Quso (ex-Vidyo)",
    featured: true,
    badgeText: "Best for Repurposing",
    category: "Content Creation",
    icon: Video,
    affiliateLink: "https://vidyo.ai?via=gzs7oi",
    metric: "10x Faster",
    metricLabel: "Content Output",
    descFreelancer: "Scale your content marketing pipeline. Automatically repurpose long-form videos into high-converting short assets.",
    descBusiness: "Scale your agency's content pipeline. Automatically convert webinars, town halls, and long-form corporate videos into branded, social-ready clips in bulk.",
    imagePath: "/quso.png",
    longDescription: "Quso (ex-Vidyo) revolutionizes the way marketing teams repurpose long-form video content. By leveraging advanced AI, it automatically identifies engaging moments in webinars and town halls, instantly converting them into high-converting, branded short clips for social media. This drastically cuts down video editing times and ensures a consistent flow of enterprise content.",
    features: [
      "Automated clip generation",
      "Brand kit customization",
      "AI virality scoring",
      "Multi-platform aspect ratios"
    ],
    ctaText: "Try for Free",
    faq: [
      {
        question: "What exactly does Quso (ex-Vidyo) do?",
        answer: "Quso uses AI to automatically repurpose long-form videos (like podcasts, webinars, or streams) into short, highly engaging clips optimized for TikTok, YouTube Shorts, and Instagram Reels. It handles scene selection, auto-framing, and generates dynamic subtitles."
      },
      {
        question: "Can I customize the look of the subtitles?",
        answer: "Yes. You have full control over the visual style. You can customize fonts, colors, and layout, or use pre-built templates to ensure your short videos perfectly match your brand identity."
      },
      {
        question: "Does Quso support languages other than English?",
        answer: "Absolutely. The AI accurately transcribes and generates captions in multiple languages, making it incredibly easy to localize your content and reach a global audience without manual translation."
      }
    ]
  },
  {
    id: "invideo-ai",
    name: "InVideo AI",
    featured: true,
    badgeText: "Best for Generation",
    category: "Content Creation",
    icon: Wand2,
    affiliateLink: "https://invideo.sjv.io/E0Ja09",
    metric: "5M+",
    metricLabel: "Active Creators",
    metricBusiness: "5000+",
    metricLabelBusiness: "Global Brands",
    descFreelancer: "Turn text prompts into professional, studio-quality videos in minutes.",
    descBusiness: "Turn text prompts into professional, studio-quality videos in minutes.",
    imagePath: "/invideo.png",
    longDescription: "InVideo AI empowers enterprise marketing teams to produce broadcast-quality video ads in minutes using simple text prompts. It eliminates the need for expensive production studios, enabling rapid iteration of creative assets for global campaigns. With seamless stock media integration and automated voiceovers, scaling video content has never been more efficient.",
    features: [
      "AI Twin Technology: Create a photorealistic digital avatar to generate faceless videos without ever stepping in front of a camera.",
      "UGC Ad Generator (AI Actor): Produce high-converting, user-generated content ads for your products without hiring real actors or renting expensive studios.",
      "Complete Prompt-to-Video: Instantly generate engaging scripts, human-like voiceovers in 50+ languages, and relevant stock footage from a single simple text prompt."
    ],
    ctaText: "Try InVideo AI for Free",
    bestFor: "B2B marketers and content teams looking to scale personalized video production while cutting costs.",
    faq: [
      {
        question: "What makes InVideo AI different from traditional video editors?",
        answer: "Instead of editing timelines manually, InVideo AI generates a complete video based purely on text prompts. The AI writes the script, selects relevant stock footage, adds a human-sounding voiceover, and applies background music automatically, reducing production time from hours to seconds."
      },
      {
        question: "Can I edit the video after the AI generates it?",
        answer: "Yes, completely. You can make adjustments by simply typing commands to the AI (e.g., \"replace this video clip\" or \"change the voiceover tone\"), or you can use the advanced standard editor to manually tweak text, media, and transitions."
      },
      {
        question: "Is the content generated by InVideo AI safe for commercial use?",
        answer: "Yes. All images, video clips, and audio tracks used by the AI are pulled from licensed high-quality stock libraries (like Storyblocks and Shutterstock). You can safely use the generated videos for YouTube, ads, marketing campaigns, and social media without worrying about copyright strikes."
      }
    ]
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    featured: true,
    badgeText: "Best for Voiceovers",
    category: "Content Creation",
    icon: Mic2,
    affiliateLink: "https://try.elevenlabs.io/47hmho07qp70",
    metric: "Ultra-HD",
    metricLabel: "Voice Quality",
    descFreelancer: "Add premium, ultra-realistic voiceovers to your corporate projects instantly. Produce high-quality audio without hiring voice actors.",
    descBusiness: "Automate voiceovers for marketing campaigns, tutorials, and ads. Drastically reduce audio production costs and turnaround times.",
    imagePath: "/elevenlabs.png",
    longDescription: "ElevenLabs is the industry leader in ultra-realistic AI voice synthesis, providing businesses with studio-quality audio instantly. It allows enterprises to clone voices, generate highly emotive voiceovers for marketing campaigns, and localize content across dozens of languages without hiring voice actors. This significantly reduces audio production costs and turnaround times.",
    features: [
      "Ultra-realistic voice synthesis",
      "Voice cloning in 29 languages",
      "Emotion and pacing control",
      "Enterprise-grade API access"
    ],
    ctaText: "Try for Free",
    faq: [
      {
        question: "What makes ElevenLabs different from other AI voice generators?",
        answer: "ElevenLabs offers hyper-realistic, emotionally expressive text-to-speech. It understands context, allowing the AI to adjust intonation, pacing, and emotion naturally, making it sound entirely human rather than robotic."
      },
      {
        question: "Can I clone my own voice using ElevenLabs?",
        answer: "Yes, the platform features a powerful Professional Voice Cloning tool. You only need to upload a clean audio sample of your voice, and the AI will create a highly accurate digital replica that you can use for any text-to-speech generation."
      },
      {
        question: "Does ElevenLabs support multiple languages?",
        answer: "Absolutely. The platform supports dozens of languages with native accents. It even offers an AI dubbing feature that can translate and dub your existing audio or video files into another language while perfectly preserving the original speaker's unique voice characteristics."
      }
    ]
  },
  {
    id: "make",
    name: "Make",
    featured: true,
    category: "Operations",
    icon: Settings,
    affiliateLink: "https://www.make.com/en/register?pc=b2baistack",
    metric: "$9/mo",
    metricLabel: "Starting Price",
    metricBusiness: "10x",
    metricLabelBusiness: "Cost Savings",
    descFreelancer: "The powerful, visual, and cost-effective alternative to Zapier.",
    descBusiness: "The powerful, visual, and cost-effective alternative to Zapier.",
    imagePath: "/make.png",
    longDescription: "Make (formerly Integromat) is the most powerful visual automation platform for businesses that want enterprise-grade workflow logic without enterprise pricing. Its drag-and-drop scenario builder lets teams design complex, multi-step automations with conditional logic, data transformation, and error handling — all without writing a single line of code. At a fraction of the cost of Zapier, Make is the go-to choice for scaling operations efficiently.",
    features: [
      "Visual Workflow Builder: Design complex automations and logic visually with an intuitive drag-and-drop interface, no coding required.",
      "Unbeatable Pricing: Automate your business processes at a fraction of the cost of legacy tools like Zapier (get thousands of tasks for just $9/month).",
      "Limitless Integrations: Connect to thousands of apps out-of-the-box or use advanced HTTP/webhook modules to integrate any API on the web."
    ],
    ctaText: "Start Automating for Free",
    bestFor: "B2B founders, operations managers, and developers looking to scale automations while radically cutting software costs.",
    faq: [
      {
        question: "Is Make.com better than Zapier?",
        answer: "Many advanced users prefer Make because of its highly visual, drag-and-drop interface that allows for unlimited branching, complex routing, and multi-step automations. Plus, it generally offers a much more cost-effective pricing structure compared to Zapier."
      },
      {
        question: "Do I need to know how to code to use Make?",
        answer: "No, Make is a powerful no-code platform. You build workflows by visually connecting app modules. However, if you are a developer, you can still use advanced features like JSON parsing, custom API calls, and webhooks."
      },
      {
        question: "What kind of apps can I automate with Make?",
        answer: "Make integrates seamlessly with thousands of popular applications, including CRMs, social media platforms, Google Workspace, Slack, and AI tools like OpenAI. If an app has an API, you can likely connect it using Make's HTTP module."
      }
    ]
  },
  {
    id: "chatbase",
    name: "Chatbase",
    featured: true,
    category: "Customer Support",
    icon: MessageSquare,
    affiliateLink: "https://link.chatbase.co/igor-pinyugin",
    metric: "80%",
    metricLabel: "Query Automation",
    metricBusiness: "2 min",
    metricLabelBusiness: "Setup Time",
    descFreelancer: "Build a custom AI chatbot from your data in seconds and slash support costs.",
    descBusiness: "Build a custom AI chatbot from your data in seconds and slash support costs.",
    imagePath: "/chatbase.png",
    longDescription: "Chatbase is the fastest way to deploy a custom AI assistant trained entirely on your own content. Upload a PDF, paste a URL, or drop in plain text — and within minutes you have a fully functional support bot that handles queries 24/7. It automates up to 80% of repetitive customer questions at a fraction of the cost of legacy platforms like Intercom, and deploys on your site with a single line of code.",
    features: [
      "Train on Your Data: Simply upload a PDF, add a website link, or paste text to generate a fully functional AI assistant in under 2 minutes.",
      "The Cost-Effective Intercom Alternative: Automate up to 80% of customer queries 24/7 without the massive price tag of legacy support platforms.",
      "Seamless Integration: Embed the chat widget on your website with a single line of code, or connect it directly to Slack, Zapier, and WhatsApp."
    ],
    ctaText: "Build Your Free AI Bot",
    bestFor: "B2B SaaS founders, agencies, and customer success teams looking to instantly scale support without expanding headcount.",
    faq: [
      {
        question: "How do I train Chatbase on my own data?",
        answer: "Training is incredibly simple. You can upload files (PDF, DOCX, TXT), paste raw text, or just provide a link to your website. Chatbase will automatically crawl and ingest your content to build a custom AI chatbot that knows your business inside and out."
      },
      {
        question: "How do I add the Chatbase widget to my website?",
        answer: "Once your chatbot is trained, Chatbase provides a simple embed code (iframe or script tag). You can easily paste this into any website builder, including Webflow, WordPress, Shopify, or Wix, to display a live chat bubble for your visitors."
      },
      {
        question: "Can the chatbot capture leads?",
        answer: "Yes. You can configure Chatbase to ask visitors for their name, email, or phone number before or during the conversation. This turns your AI support bot into an automated 24/7 lead generation machine."
      }
    ]
  },
  {
    id: "fireflies-ai",
    name: "Fireflies.ai",
    featured: true,
    badgeText: "Best AI Notetaker",
    category: "AI Meetings & Intelligence",
    categories: ["AI Meetings & Intelligence", "Sales"],
    icon: Mic2,
    affiliateLink: "https://fireflies.ai/?fpr=b2baistack",
    metric: "100%",
    metricLabel: "Meetings Captured",
    metricBusiness: "0 min",
    metricLabelBusiness: "Manual Notes",
    descFreelancer: "Automate your meeting notes and boost sales productivity with an AI voice assistant.",
    descBusiness: "Automate your meeting notes and boost sales productivity with an AI voice assistant.",
    imagePath: "/fireflies.png",
    longDescription: "Fireflies.ai is an AI-powered meeting assistant that automatically records, transcribes, and summarizes every conversation across Zoom, Google Meet, and Microsoft Teams. It extracts action items, key decisions, and conversation intelligence instantly after each call — then pushes everything directly into your CRM, Notion, or Slack. Sales teams close more deals and ops teams stay aligned without ever writing a manual note again.",
    features: [
      "Automated Note-Taking: Instantly record and transcribe meetings across Zoom, Google Meet, and Teams without lifting a finger.",
      "AI-Powered Summaries: Get instant action items, conversational intelligence, and key takeaways generated automatically after every call.",
      "Seamless CRM Integration: Push meeting notes and actionable tasks directly into your CRM (HubSpot, Salesforce), Notion, and Slack."
    ],
    ctaText: "Start for Free",
    bestFor: "Sales teams, operations managers, and B2B founders looking to eliminate manual note-taking and capture every crucial detail."
  },
  {
    id: "heygen",
    name: "HeyGen",
    featured: false,
    category: "Sales",
    icon: Users,
    affiliateLink: "https://www.heygen.com/",
    metric: "120+",
    metricLabel: "Languages",
    descFreelancer: "Create professional AI avatar videos for corporate campaigns. Produce premium presentation and marketing videos at lightning speed.",
    descBusiness: "Scale personalized video outreach and corporate training with AI avatars. Stop paying for expensive talent and studio time.",
    imagePath: "/heygen.png",
    longDescription: "HeyGen transforms personalized video outreach by generating professional AI avatars for sales, marketing, and corporate training. It allows teams to create scalable, human-like video presentations simply by typing text, entirely replacing the need for on-camera talent or studio time. Secure, localized, and easily integrated, HeyGen is built for modern enterprise communication.",
    features: [
      "Custom AI avatars",
      "Text-to-speech in 120+ languages",
      "Automated personalized video campaigns",
      "Enterprise security and SSO"
    ],
    ctaText: "Try for Free",
    expertRecommendation: "HeyGen is the industry leader for AI-generated avatars and personalized talking-head videos. However, if you are looking for a comprehensive AI video editor to create marketing promos, explainer videos, or social content from text using stock footage, our Top Pick [InVideo](https://invideo.sjv.io/E0Ja09) is often a more versatile and cost-effective choice for general B2B video production.\n\nCheck out [InVideo](https://invideo.sjv.io/E0Ja09) if you prioritize high-quality editing and storytelling over avatar-based talking heads."
  },
  {
    id: "creatify-ai",
    name: "Creatify AI",
    featured: false,
    category: "AI Ads",
    categories: ["Marketing", "AI Ads"],
    icon: ShoppingBag,
    affiliateLink: "https://creatify.ai/?via=b2baistack",
    metric: "ROI",
    metricLabel: "Optimized Ads",
    descFreelancer: "Generate unlimited high-performing ads from product links. Provide highly profitable ad creatives to B2B clients faster.",
    descBusiness: "Generate converting video ads directly from your product URLs. Replace costly UGC agencies with an automated AI pipeline.",
    imagePath: "/creatify.png",
    longDescription: "Creatify AI streamlines the creation of high-performing video ads by generating unlimited variations directly from product URLs. It allows performance marketing teams to rapidly test ad creatives, replacing costly UGC agencies with an automated, AI-driven pipeline. Maximize ROI and dramatically increase your creative testing velocity.",
    features: [
      "URL-to-video ad generation",
      "AI-driven script writing",
      "Automated A/B testing variations",
      "E-commerce platform integrations"
    ],
    ctaText: "Visit Creatify (-15%)",
    faq: [
      {
        question: "How does Creatify AI generate video ads?",
        answer: "You simply paste a product URL (like an Amazon or Shopify link). The AI automatically extracts the product details, writes an engaging script, and generates a high-quality, UGC-style video ad using highly realistic AI avatars and voiceovers."
      },
      {
        question: "Are the AI avatars suitable for User-Generated Content (UGC) ads?",
        answer: "Yes, the avatars are specifically designed to look and sound like real content creators. This native, authentic feel is perfect for TikTok, Instagram Reels, and Meta Ads, significantly lowering your Cost Per Acquisition (CPA)."
      },
      {
        question: "Can I edit the video script or change the AI voice?",
        answer: "Absolutely. While the AI does the heavy lifting, you have full creative control to rewrite the script, swap out the avatar, change the voice, or upload your own B-roll footage before exporting the final video."
      }
    ]
  },
  {
    id: "intercom-fin",
    slug: "intercom-fin",
    name: "Intercom Fin",
    category: "Customer Support",
    icon: MessageSquare,
    affiliateLink: "https://www.intercom.com/",
    websiteUrl: "https://www.intercom.com/",
    metric: "50%+",
    metricLabel: "Resolution Rate",
    shortDescription: "Deploy a breakthrough AI bot that resolves complex customer issues instantly using your support content.",
    descFreelancer: "Automate client support with an AI agent. Reduce ticket volume and provide instant answers 24/7.",
    descBusiness: "Deploy a breakthrough AI bot that resolves complex customer issues instantly using your support content. Drastically reduce human intervention.",
    imagePath: "https://image.thum.io/get/width/1200/crop/675/https://www.intercom.com/",
    longDescription: "Intercom Fin is an enterprise-grade AI support bot designed to resolve customer inquiries instantly. By ingesting your existing knowledge base and past tickets, Fin provides highly accurate, conversational answers that drastically reduce human agent workload. It guarantees a faster time-to-resolution, improving overall CSAT scores and scaling your support operations effortlessly.",
    features: [
      "Zero-setup AI training",
      "Human handoff capabilities",
      "Multilingual support",
      "Deep Zendesk and Salesforce integration"
    ],
    ctaText: "Get Started"
  },
  {
    id: "gong",
    slug: "gong",
    name: "Gong",
    category: "Sales",
    categories: ["Sales", "AI Meetings & Intelligence"],
    icon: TrendingUp,
    affiliateLink: "https://www.gong.io/",
    websiteUrl: "https://www.gong.io/",
    metric: "44%",
    metricLabel: "Win Rate Increase",
    shortDescription: "Uncover revenue intelligence with AI-driven analysis of every customer interaction and sales call.",
    descFreelancer: "Analyze your client calls to uncover insights. Improve your pitching and close more deals.",
    descBusiness: "Uncover revenue intelligence with AI-driven analysis of every customer interaction and sales call. Maximize your team's win rates.",
    imagePath: "https://image.thum.io/get/width/1200/crop/675/https://www.gong.io/",
    longDescription: "Gong captures and analyzes every customer interaction—across phone, email, and web conferencing—to deliver powerful revenue intelligence. Its advanced AI surfaces deal risks, identifies winning sales behaviors, and automates CRM data entry. By providing complete visibility into the sales pipeline, Gong empowers enterprise teams to close more deals faster and with higher predictability.",
    features: [
      "Automated conversation analytics",
      "Deal execution tracking",
      "AI-generated CRM updates",
      "Sales coaching insights"
    ],
    ctaText: "Request Demo"
  },
  {
    id: "eightfold-ai",
    slug: "eightfold-ai",
    name: "Eightfold AI",
    category: "HR",
    icon: Briefcase,
    affiliateLink: "https://eightfold.ai/",
    websiteUrl: "https://eightfold.ai/",
    metric: "90%",
    metricLabel: "Faster Screening",
    shortDescription: "Transform talent acquisition and management with an AI-powered platform for the modern enterprise.",
    descFreelancer: "Use AI to match the best candidates for your agency. Streamline hiring and onboarding.",
    descBusiness: "Transform talent acquisition and management with an AI-powered platform. Hire, retain, and grow your enterprise workforce efficiently.",
    imagePath: "https://image.thum.io/get/width/1200/crop/675/https://eightfold.ai/",
    longDescription: "Eightfold AI offers a comprehensive Talent Intelligence Platform that transforms how enterprises hire, retain, and grow their workforce. Utilizing deep learning, it matches candidates to roles based on potential and skills rather than just pedigree, significantly reducing time-to-hire. This AI-first approach mitigates bias, enhances diversity, and drives strategic workforce planning at a global scale.",
    features: [
      "AI-driven candidate matching",
      "Skills-based workforce planning",
      "Automated talent nurturing",
      "Diversity and inclusion analytics"
    ],
    ctaText: "Explore Platform"
  },
  {
    id: "uipath-autopilot",
    slug: "uipath-autopilot",
    name: "UiPath Autopilot",
    category: "Operations",
    icon: Settings,
    affiliateLink: "https://www.uipath.com/",
    websiteUrl: "https://www.uipath.com/",
    metric: "3x",
    metricLabel: "Process Speed",
    shortDescription: "Automate complex enterprise workflows natively with AI-powered RPA and document processing.",
    descFreelancer: "Automate repetitive data entry and manual tasks. Free up your time for strategic work.",
    descBusiness: "Automate complex enterprise workflows natively with AI-powered RPA and document processing. Drastically reduce operational costs.",
    imagePath: "https://image.thum.io/get/width/1200/crop/675/https://www.uipath.com/",
    longDescription: "UiPath Autopilot infuses generative AI across the entire automation lifecycle, enabling enterprises to build and manage complex workflows with unprecedented ease. It combines world-class Robotic Process Automation (RPA) with intelligent document processing to automate tedious operational tasks natively. This unified platform accelerates digital transformation and significantly lowers enterprise operational costs.",
    features: [
      "Generative AI workflow creation",
      "Intelligent document processing",
      "Cross-platform RPA integration",
      "Enterprise-grade security and governance"
    ],
    ctaText: "Try for Free"
  },
  {
    id: "github-copilot",
    slug: "github-copilot",
    name: "GitHub Copilot",
    category: "IT & Dev",
    icon: Code2,
    affiliateLink: "https://github.com/features/copilot",
    websiteUrl: "https://github.com/features/copilot",
    metric: "55%",
    metricLabel: "Faster Coding",
    shortDescription: "Accelerate software development with the world's most widely adopted AI pair programmer.",
    descFreelancer: "Write code faster with AI auto-completion. Ship client projects ahead of schedule.",
    descBusiness: "Accelerate software development with the world's most widely adopted AI pair programmer. Boost engineering team velocity.",
    imagePath: "https://image.thum.io/get/width/1200/crop/675/https://github.com/features/copilot",
    longDescription: "GitHub Copilot is the industry standard AI pair programmer, designed to radically increase engineering velocity. By offering context-aware code suggestions directly within the IDE, it eliminates boilerplate coding and helps developers focus on complex logic. Deployed across the enterprise, Copilot enhances code quality, accelerates time-to-market, and significantly boosts overall developer happiness.",
    features: [
      "Context-aware code completion",
      "Natural language to code",
      "Enterprise IP indemnification",
      "IDE and CLI integration"
    ],
    ctaText: "Start Free Trial"
  },
  {
    id: "cursor",
    slug: "cursor",
    name: "Cursor",
    category: "IT & Dev",
    icon: Cpu,
    affiliateLink: "https://www.cursor.com/",
    websiteUrl: "https://www.cursor.com/",
    metric: "2x",
    metricLabel: "Dev Productivity",
    shortDescription: "Build software faster in an AI-first code editor designed for deep codebase understanding.",
    descFreelancer: "Navigate and refactor large codebases instantly. A must-have IDE for modern web development.",
    descBusiness: "Build software faster in an AI-first code editor designed for deep codebase understanding. Seamlessly integrate AI into your engineering workflow.",
    imagePath: "https://image.thum.io/get/width/1200/crop/675/https://www.cursor.com/",
    longDescription: "Cursor is an AI-first IDE built to understand your entire codebase natively. It allows engineering teams to edit, refactor, and debug complex applications through a conversational interface directly in their development environment. By seamlessly integrating large language models with the text editor, Cursor drastically reduces cognitive load and doubles developer productivity.",
    features: [
      "Codebase-wide semantic search",
      "AI-driven refactoring",
      "Integrated terminal debugging",
      "Privacy-first enterprise mode"
    ],
    ctaText: "Download Free"
  },
  {
    id: "zendesk-ai",
    slug: "zendesk-ai",
    name: "Zendesk AI",
    category: "Customer Support",
    icon: HeadphonesIcon,
    affiliateLink: "https://www.zendesk.com/ai/",
    websiteUrl: "https://www.zendesk.com/ai/",
    metric: "30%",
    metricLabel: "Ticket Deflection",
    shortDescription: "Scale your customer service operations instantly with built-in AI agents and insights.",
    descFreelancer: "Manage client queries efficiently with AI categorizations and auto-responses.",
    descBusiness: "Scale your customer service operations instantly with built-in AI agents and insights. Deliver exceptional enterprise support at scale.",
    imagePath: "https://image.thum.io/get/width/1200/crop/675/https://www.zendesk.com/ai/",
    longDescription: "Zendesk AI empowers enterprise support teams by integrating intelligent automation directly into the service workflow. It instantly categorizes incoming tickets, suggests macro responses to agents, and deploys advanced bots to deflect common inquiries. This holistic AI approach reduces resolution times, lowers support costs, and guarantees a seamless, highly personalized customer experience.",
    features: [
      "Intelligent ticket routing",
      "Agent assist macros",
      "Custom AI intent models",
      "Comprehensive sentiment analysis"
    ],
    ctaText: "See in Action",
    expertRecommendation: "Zendesk is the established enterprise standard for customer support and ticketing. However, it can be expensive and requires significant time to set up and train staff. For B2B teams looking for an immediate, AI-driven solution, our Top Pick [Chatbase](https://www.chatbase.co/?via=igor-pinyugin&dub_id=mVuJAivF7SHhGuKy) is a game-changer. It allows you to build a custom AI chatbot trained on your own website and data in just minutes, handling support queries automatically without the enterprise overhead.\n\nCheck out [Chatbase](https://www.chatbase.co/?via=igor-pinyugin&dub_id=mVuJAivF7SHhGuKy) if you need a cost-effective, zero-code AI support agent today."
  },
  {
    id: "apollo-ai",
    slug: "apollo-ai",
    name: "Apollo AI",
    category: "Sales",
    icon: LineChart,
    affiliateLink: "https://www.apollo.io/",
    websiteUrl: "https://www.apollo.io/",
    metric: "200M+",
    metricLabel: "B2B Contacts",
    shortDescription: "Automate outbound prospecting and personalized email outreach with a hyper-accurate B2B database.",
    descFreelancer: "Find your ideal agency clients and automate your cold email outreach seamlessly.",
    descBusiness: "Automate outbound prospecting and personalized email outreach with a hyper-accurate B2B database. Fill your sales pipeline automatically.",
    imagePath: "https://image.thum.io/get/width/1200/crop/675/https://www.apollo.io/",
    longDescription: "Apollo AI revolutionizes B2B sales prospecting by combining a massive, highly accurate contact database with generative AI outreach. It automatically identifies ideal buyer personas, drafts hyper-personalized cold emails, and manages multi-channel engagement sequences. This end-to-end platform ensures that enterprise sales teams maintain a consistently full pipeline with minimal manual effort.",
    features: [
      "AI-generated personalized emails",
      "Automated sequence management",
      "Real-time intent data",
      "Seamless CRM synchronization"
    ],
    ctaText: "Start for Free"
  },
  {
    id: "paradox",
    slug: "paradox",
    name: "Paradox",
    category: "HR",
    icon: Users,
    affiliateLink: "https://www.paradox.ai/",
    websiteUrl: "https://www.paradox.ai/",
    metric: "99%",
    metricLabel: "Candidate CSAT",
    shortDescription: "Automate candidate screening and interview scheduling with Olivia, the conversational recruiting assistant.",
    descFreelancer: "Automate candidate vetting and calendar scheduling. Save hours on recruitment admin.",
    descBusiness: "Automate candidate screening and interview scheduling with Olivia, the conversational recruiting assistant. Accelerate high-volume enterprise hiring.",
    imagePath: "https://image.thum.io/get/width/1200/crop/675/https://www.paradox.ai/",
    longDescription: "Paradox introduces Olivia, a conversational AI assistant that completely automates the top of the hiring funnel for enterprises. It handles candidate screening, answers FAQs in real-time, and seamlessly coordinates complex interview schedules via text and web chat. By removing administrative bottlenecks, Paradox dramatically accelerates high-volume hiring and delivers a frictionless candidate experience.",
    features: [
      "Conversational AI screening",
      "Automated interview scheduling",
      "SMS and WhatsApp integration",
      "High-volume hiring optimization"
    ],
    ctaText: "Book Demo"
  },
  {
    id: "juicebox",
    slug: "juicebox",
    name: "Juicebox",
    featured: true,
    badgeText: "Best for Sourcing",
    category: "HR",
    icon: Users,
    affiliateLink: "https://juicebox.ai/?via=742235",
    websiteUrl: "https://juicebox.ai/?via=742235",
    metric: "800M+",
    metricLabel: "Profiles",
    shortDescription: "Find, filter, and outreach to top-tier candidates in seconds using AI natural language search.",
    descFreelancer: "Find, filter, and outreach to top-tier candidates in seconds using AI natural language search.",
    descBusiness: "Find, filter, and outreach to top-tier candidates in seconds using AI natural language search.",
    imagePath: "https://image.thum.io/get/width/1200/crop/675/https://juicebox.ai/",
    longDescription: "Traditional recruiting tools require complex search strings and hours of manual filtering. Juicebox completely redefines the sourcing process by allowing you to search for talent the same way you talk to a human researcher. Whether you need a \"Senior Python Developer\" or a \"Growth Marketer,\" the AI understands the context instantly. It crawls through deep professional data across multiple platforms, builds a highly accurate shortlist, and handles automated, personalized email outreach to candidates.",
    features: [
      "Instant Sourcing: Turn days of manual searching into a 60-second AI task.",
      "Cross-Platform Intelligence: Aggregates public data from 30+ verified sources to find hidden talent.",
      "Automated Outreach: Drafts highly personalized emails and syncs replies directly with your CRM/ATS."
    ],
    ctaText: "Try Juicebox Free",
    faq: [
      {
        question: "Does Juicebox replace a human recruiter?",
        answer: "No, it replaces the manual \"sourcing\" phase. Juicebox handles 90% of the tedious work, allowing you to focus entirely on interviewing and closing warm candidates."
      },
      {
        question: "Where does Juicebox get its candidate data?",
        answer: "It aggregates public data from over 30 different sources, not just LinkedIn, uncovering passive candidates."
      },
      {
        question: "Can I integrate Juicebox with my existing ATS?",
        answer: "Yes. Juicebox syncs seamlessly with all major ATS and CRM platforms."
      }
    ]
  },
  {
    id: "zapier-central",
    slug: "zapier-central",
    name: "Zapier Central",
    category: "Operations",
    icon: Wand2,
    affiliateLink: "https://zapier.com/central/",
    websiteUrl: "https://zapier.com/central/",
    metric: "6000+",
    metricLabel: "Integrations",
    shortDescription: "Build custom AI bots that interact with thousands of business apps to automate entire workflows.",
    descFreelancer: "Connect your apps with an AI bot that executes tasks across your software stack automatically.",
    descBusiness: "Build custom AI bots that interact with thousands of business apps to automate entire workflows. Unify your enterprise data silos.",
    imagePath: "https://image.thum.io/get/width/1200/crop/675/https://zapier.com/central/",
    longDescription: "Zapier Central allows enterprises to build autonomous AI bots that seamlessly interact with over 6,000 business applications. Unlike traditional rigid workflows, Central’s bots understand natural language commands to pull data, update records, and trigger complex operational sequences across disparate software silos. It provides a secure, centralized hub to manage automation and radically boost organizational efficiency.",
    features: [
      "Natural language task execution",
      "Access to 6,000+ app integrations",
      "Real-time data syncing",
      "Custom AI behavior training"
    ],
    ctaText: "Try Central",
    expertRecommendation: "Zapier Central is a powerful automation assistant. However, for B2B teams building complex, visual, and highly scalable workflows, our Top Pick [Make](https://www.make.com/en/register?pc=b2baistack) offers significantly more flexibility and cost-efficiency. It allows for advanced visual logic that handles intricate multi-step processes with ease.\n\nCheck out [Make](https://www.make.com/en/register?pc=b2baistack) if you need a professional-grade automation engine."
  },
  {
    id: "zapier",
    slug: "zapier",
    name: "Zapier",
    category: "Operations",
    icon: Wand2,
    affiliateLink: "https://zapier.com/",
    websiteUrl: "https://zapier.com/",
    metric: "7000+",
    metricLabel: "App Integrations",
    shortDescription: "Automate repetitive tasks by connecting your apps with simple, no-code trigger-action workflows.",
    descFreelancer: "Connect your favourite apps and automate repetitive tasks without writing a single line of code.",
    descBusiness: "Automate repetitive tasks by connecting your apps with simple, no-code trigger-action workflows. Reduce manual busywork across your entire organization.",
    imagePath: "https://image.thum.io/get/width/1200/crop/675/https://zapier.com/",
    longDescription: "Zapier is one of the most widely adopted no-code automation platforms, enabling businesses to connect over 7,000 apps with simple trigger-and-action workflows known as 'Zaps'. Without writing any code, teams can automate repetitive tasks — from syncing CRM data and sending notifications to managing leads and filing reports — across virtually any software stack. It lowers the barrier to automation for non-technical users and helps organizations eliminate manual busywork at scale.",
    features: [
      "7,000+ app integrations",
      "No-code workflow builder",
      "Multi-step Zap automation",
      "Conditional logic and filters"
    ],
    ctaText: "Try Zapier Free",
    expertRecommendation: "Zapier is widely known for connecting apps with simple, linear triggers. However, as B2B workflows scale, it often becomes cost-prohibitive and restrictive. For teams building complex, multi-step automated processes, our Top Pick [Make](https://www.make.com/en/register?pc=b2baistack) is a significantly more robust and cost-effective solution. Its visual interface allows you to design, build, and orchestrate advanced enterprise-grade automations without breaking the budget.\n\nCheck out [Make](https://www.make.com/en/register?pc=b2baistack) if you need a professional-grade automation engine."
  },
  {
    id: "zoom",
    slug: "zoom",
    name: "Zoom",
    category: "Sales",
    categories: ["Sales", "AI Meetings & Intelligence"],
    icon: Users,
    affiliateLink: "https://zoom.us/",
    websiteUrl: "https://zoom.us/",
    metric: "300M+",
    metricLabel: "Daily Participants",
    shortDescription: "Run high-fidelity video meetings, webinars, and collaborative sessions at enterprise scale with the world's leading video conferencing platform.",
    descFreelancer: "Host professional client meetings and webinars with studio-quality HD video and one-click screen sharing.",
    descBusiness: "Run high-fidelity video meetings, webinars, and collaborative sessions at enterprise scale. Trusted by over 300 million daily participants worldwide.",
    imagePath: "/zoom.png",
    longDescription: "Zoom is the undisputed global standard for enterprise video conferencing, enabling organizations of all sizes to host high-definition meetings, large-scale webinars, and real-time collaborative sessions from any device, anywhere in the world. Its platform delivers exceptional audio-visual quality with minimal latency, supporting everything from one-on-one sales calls to all-hands broadcasts with thousands of attendees. For B2B teams, Zoom eliminates geographic barriers and keeps distributed workforces fully aligned and productive.\n\nBeyond core video meetings, Zoom's enterprise suite includes Zoom Webinars for marketing events and product launches, Zoom Phone for cloud telephony, and Zoom Rooms for in-office meeting hardware. Deep integrations with Salesforce, HubSpot, Slack, Google Workspace, and Microsoft 365 make it a natural hub within any modern B2B tech stack. IT administrators benefit from granular security controls, SSO, and SOC 2 Type II compliance, making enterprise-wide rollout straightforward and auditable.\n\nZoom's reliability and universal adoption mean that prospects, clients, and partners are almost always already familiar with the platform — removing friction from every external meeting and demo.",
    features: [
      "HD video meetings with up to 1,000 participants",
      "Screen sharing, whiteboards, and breakout rooms",
      "Zoom Webinars for large-scale marketing and product events",
      "Enterprise integrations: Salesforce, HubSpot, Slack, Google Workspace",
      "End-to-end encryption and SOC 2 Type II compliance"
    ],
    ctaText: "Get Started Free",
    expertRecommendation: "Zoom is the universal standard for video conferencing. However, simply recording calls is only half the battle. For B2B sales and operations teams who need to turn meetings into actionable data, our Top Pick [Fireflies.ai](https://fireflies.ai/?fpr=b2baistack) is an essential upgrade. It automatically transcribes, summarizes, and extracts action items from your Zoom calls, routing the intelligence directly into your CRM.\n\nCheck out [Fireflies.ai](https://fireflies.ai/?fpr=b2baistack) to automate your meeting notes and boost sales productivity."
  },
  {
    id: "otter-ai",
    slug: "otter-ai",
    name: "Otter.ai",
    category: "AI Meetings & Intelligence",
    categories: ["AI Meetings & Intelligence"],
    icon: Mic2,
    affiliateLink: "https://otter.ai/",
    websiteUrl: "https://otter.ai/",
    metric: "Real-Time",
    metricLabel: "Transcription",
    shortDescription: "Get real-time AI transcription, automated meeting summaries, and instant action items synced to your team.",
    descFreelancer: "Capture every word from client meetings with live transcription and instant shareable summaries.",
    descBusiness: "Empower your entire team with real-time meeting transcription, automated summaries, and action items that sync instantly into your workspace.",
    imagePath: "https://image.thum.io/get/width/1200/crop/675/https://otter.ai/",
    longDescription: "Otter.ai delivers real-time AI transcription and meeting intelligence that transforms how B2B teams capture and act on information from every conversation. It automatically joins your Zoom, Google Meet, and Teams calls to produce live, searchable transcripts, generate concise summaries, and highlight action items within seconds of a meeting ending. For sales teams, ops leads, and managers, Otter.ai eliminates the administrative burden of note-taking and ensures nothing falls through the cracks — from client discovery calls to internal stand-ups.",
    features: [
      "Live real-time transcription across Zoom, Meet, and Teams",
      "Automated meeting summaries and action item extraction",
      "Collaborative notes with highlights and comments",
      "Instant sharing and searchable meeting archive"
    ],
    ctaText: "Try Otter Free",
    expertRecommendation: "Otter.ai excels at real-time transcription and team collaboration around meeting notes. For teams that also need deep CRM integration and full conversation intelligence (call scoring, deal risk analysis, pipeline updates), our Top Pick [Fireflies.ai](https://fireflies.ai/?fpr=b2baistack) provides a more complete end-to-end solution that pushes data directly into HubSpot and Salesforce automatically.\n\nCheck out [Fireflies.ai](https://fireflies.ai/?fpr=b2baistack) if you need automated CRM sync and sales intelligence on top of transcription."
  }
];
